### ISSUE TITLE
jumpjet单位类型索敌方式不正常

### ISSUE THREAD

**Issue by wenrui1245** [ChrisLv-CN/KratosPP#2]
在1.001版本的yr中仅加入Ares3.0p1与kratos v0.1.13，出现了以下问题（以镭射幽浮[DISK]这个单位举例）：
_镭射幽浮移动时遇到敌人→正常索敌并主动攻击进入射程范围内的敌人（正常，未出现bug）_
**指定镭射幽浮移动到某一地点待命，此时有敌人路过→镭射幽浮完全不主动攻击敌人，受击后也不会有任何反应（纯yr不会出现这种问题）
**给单位加CanPassiveAquire=yes、JumpjetFacingToTarget=yes也不会自动攻击/反击射程内空中目标**
选中镭射幽浮并手动攻击敌人→敌人死亡后继续索敌并攻击，但是只攻击一次敌人便停止（纯yr不会出现这种问题）**
不清楚是wwsb，ini中语句写了yr中不生效的语句，但kratos修复了，所以导致此问题，还是kratos的bug。

**Comment by ChrisLv-CN** [comment]
无法复现
