### ISSUE TITLE
超时空传送Aircraft会引发游戏IE

### ISSUE THREAD

**Issue by wenrui1245** [ChrisLv-CN/KratosPP#3]
1.001YR，Ares3.0p1，kratosv0.1.13
使用超时空传送在机场上停放的飞机会引发游戏IE
**若在[AudioVisual]中加入语句DisableAircraftAutoPitch=yes，则飞机可以被正常传送，游戏正常运行，疑似是Aircraft被超时空传送以后想抬头起飞？**

**Comment by ChrisLv-CN** [comment]
该问题已于0.1.13惨遭修复
